version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: l5_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: my_relational_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo_db:
    image: mongo:6.0
    container_name: l5_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  review_service:
    build: ./ShopSphere-review-service
    container_name: l5_review_service
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://rootuser:rootpassword@mongo_db:27017/my_document_db?authSource=admin
    depends_on:
      - mongo_db

  backend_api:
    build: ./backend
    container_name: l5_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=super_secret_jwt_key_deci_level5
      - DATABASE_URL=postgresql://myuser:mypassword@postgres_db:5432/my_relational_db?schema=public
      - MONGO_URI=mongodb://rootuser:rootpassword@mongo_db:27017/my_document_db?authSource=admin
      - REVIEW_SERVICE_URL=http://review_service:5001
      - SERVERLESS_EMAIL_URL=https://shopsphere-serverless-email.vercel.app/api/send-welcome-email
    depends_on:
      - postgres_db
      - mongo_db
      - review_service
    volumes:
      - backend_uploads:/usr/src/app/public/uploads
    command: >
      sh -c "npx prisma generate && 
             npx prisma db push && 
             npx prisma db seed && 
             npm start"
                        
  frontend_app:
    build: ./frontend
    container_name: l5_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend_api

volumes:
  postgres_data:
  mongo_data:
  backend_uploads: