apiVersion: v1
kind: Namespace
metadata:
  name: aws-simulation
  labels:
    cloud-provider: aws
    environment: simulation
---
apiVersion: v1
kind: Namespace
metadata:
  name: gcp-simulation
  labels:
    cloud-provider: gcp
    environment: simulation
